services:
  api:
    image: mohitarroa8181/linkerin:latest
    container_name: linkerin-api
    pull_policy: always
    env_file:
      - path: ./.env
        required: true
    environment:
      NODE_ENV: production
      PORT: 3000
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
